### ISSUE TITLE
Json Path section doesn't work

### ISSUE THREAD

**Issue by redace0001** [marcelkliemannel/intellij-developer-tools-plugin#9] opened 2023-08-08 12:37 UTC
Hello.

When I try to open the JSON Path section in the module, I get this traceback :
```
java.lang.NoClassDefFoundError: com/intellij/jsonpath/JsonPathLanguage
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer.createQueryInputEditor(JsonPathTransformer.kt:103)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer.access$createQueryInputEditor(JsonPathTransformer.kt:38)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer$queryEditor$2.invoke(JsonPathTransformer.kt:56)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer$queryEditor$2.invoke(JsonPathTransformer.kt:56)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer.getQueryEditor(JsonPathTransformer.kt:56)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer.access$getQueryEditor(JsonPathTransformer.kt:38)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer$buildMiddleConfigurationUi$1.invoke(JsonPathTransformer.kt:64)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer$buildMiddleConfigurationUi$1.invoke(JsonPathTransformer.kt:63)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:58)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:20)
	at com.intellij.ui.dsl.builder.Panel.row$default(Panel.kt:76)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.JsonPathTransformer.buildMiddleConfigurationUi(JsonPathTransformer.kt:63)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.tool.transformer.TextTransformer.buildUi(TextTransformer.kt:58)
	at dev.turingcomplete.intellijdevelopertoolsplugins.DeveloperTool$createComponent$1.invoke(DeveloperTool.kt:29)
	at dev.turingcomplete.intellijdevelopertoolsplugins.DeveloperTool$createComponent$1.invoke(DeveloperTool.kt:28)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at dev.turingcomplete.intellijdevelopertoolsplugins.DeveloperTool.createComponent(DeveloperTool.kt:28)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.DeveloperToolContentPanel.addWorkbench(DeveloperToolContentPanel.kt:97)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.DeveloperToolContentPanel.createMainContent(DeveloperToolContentPanel.kt:76)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.DeveloperToolContentPanel.<init>(DeveloperToolContentPanel.kt:41)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog$handleContentNodeSelection$1.invoke(MainDialog.kt:126)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog$handleContentNodeSelection$1.invoke(MainDialog.kt:108)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog$special$$inlined$observable$1.afterChange(Delegates.kt:34)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog.setSelectedContentNode(MainDialog.kt:38)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog.access$setSelectedContentNode(MainDialog.kt:33)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog$createCenterPanel$1.invoke(MainDialog.kt:57)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainDialog$createCenterPanel$1.invoke(MainDialog.kt:57)
	at dev.turingcomplete.intellijdevelopertoolsplugins._internal.dialog.MainMenuTree.handleMenuTreeSelection$lambda-10(MainMenuTree.kt:129)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:3021)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3522)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:650)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:669)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1120)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:306)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:200)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1710)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2764)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4099)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4038)
	at com.intellij.util.ui.MouseEventAdapter.mousePressed(MouseEventAdapter.java:31)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:437)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4578)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.jsonpath.JsonPathLanguage PluginClassLoader(plugin=PluginDescriptor(name=Developer Tools, id=dev.turingcomplete.intellijdevelopertoolsplugins, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2023.2\plugins\intellij-developer-tools-plugin, version=1.0.1, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 94 more

```

----------------

I'm using PyCharm 2023.2 (Community Edition) on Windows 10
I'm using Developer Tools 1.0.1

Hope that helps !

**Comment by marcelkliemannel** [comment] 2023-08-14 16:46
Hi, thanks for reporting this. This is caused by an API breaking change in 2023.2 and will be fixed in the next plugin release.

**Closed by marcelkliemannel** 2023-08-14 16:46 UTC
